apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-backend-k8
  labels:
    app: flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flask-backend-k8
        image: flaskapp
        ports:
        - containerPort: 3000
