apiVersion: v1
kind: Service
metadata:
  name: flask-backend-k8-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: flaskapp
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 3000
